name: MLOps Final Project Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. تحميل الكود من المستودع
    - uses: actions/checkout@v3

    # 2. تجهيز بيئة بايثون
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. تثبيت المكتبات
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. تشغيل الاختبارات (Unit Testing)
    - name: Run Tests with Pytest
      run: |
        pytest

    # 5. بناء Docker Image (للتأكد أن Dockerfile سليم)
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag my-mlops-project:latest